# Generated by Django 6.0.3 on 2026-03-04 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catedratico', '0001_initial'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catedratico.catedratico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.curso')),
            ],
            options={
                'db_table': 'asignacion_curso',
            },
        ),
    ]
