# Generated by Django 6.0.3 on 2026-03-04 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '__first__'),
        ('Asignacion_curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumno')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignacion_curso.asignacion_curso')),
            ],
            options={
                'db_table': 'inscripcion_alumno',
            },
        ),
    ]
