# Generated by Django 6.0.3 on 2026-03-04 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inscripcion_alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscripcion_alumno.inscripcion_alumno')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
    ]
